<?php

use yii\db\Migration;


class m251126_215754_init_schema extends Migration
{

  /**
   * {@inheritdoc}
   */
  public function safeUp()
  {
    $sql = <<<SQL_EOF
-- MySQL Script generated by MySQL Workbench
-- Mon Nov 24 19:45:48 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `{{schema}}` ;
USE `{{schema}}` ;

-- -----------------------------------------------------
-- Table `{{schema}}`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `{{schema}}`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nicename` VARCHAR(255) NULL DEFAULT NULL,
  `fullname` VARCHAR(255) NULL DEFAULT NULL,
  `gender` VARCHAR(1) NOT NULL,
  `birthdate` DATE NULL DEFAULT NULL,
  `username` VARCHAR(255) NOT NULL,
  `auth_key` VARCHAR(32) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `password_reset_token` VARCHAR(255) NULL DEFAULT NULL,
  `verification_token` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` INT NULL DEFAULT NULL,
  `updated_at` INT NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`id`),
  UNIQUE INDEX `id_UNIQUE` USING BTREE (`id`) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` USING BTREE (`username`) VISIBLE,
  UNIQUE INDEX `password_reset_token_UNIQUE` USING BTREE (`password_reset_token`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `{{schema}}`.`auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `{{schema}}`.`auth` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `source` VARCHAR(255) NOT NULL,
  `source_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY USING BTREE (`id`, `user_id`),
  UNIQUE INDEX `id_UNIQUE` USING BTREE (`id`) VISIBLE,
  INDEX `fk_auth_user1_idx` USING BTREE (`user_id`) VISIBLE,
  CONSTRAINT `fk_auth_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `{{schema}}`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `{{schema}}`.`auth_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `{{schema}}`.`auth_rule` (
  `name` VARCHAR(64) CHARACTER SET 'utf8mb3' NOT NULL,
  `data` BLOB NULL DEFAULT NULL,
  `created_at` INT NULL DEFAULT NULL,
  `updated_at` INT NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`name`))
ENGINE = InnoDB
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `{{schema}}`.`auth_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `{{schema}}`.`auth_item` (
  `name` VARCHAR(64) CHARACTER SET 'utf8mb3' NOT NULL,
  `type` SMALLINT NOT NULL,
  `description` TEXT CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `rule_name` VARCHAR(64) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `data` VARCHAR(250) CHARACTER SET 'utf8mb3' NULL DEFAULT '',
  `created_at` INT NULL DEFAULT NULL,
  `updated_at` INT NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`name`),
  INDEX `rule_name` USING BTREE (`rule_name`) VISIBLE,
  INDEX `idx_auth_item_type` USING BTREE (`type`) VISIBLE,
  CONSTRAINT `auth_item_ibfk_1`
    FOREIGN KEY (`rule_name`)
    REFERENCES `{{schema}}`.`auth_rule` (`name`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `{{schema}}`.`auth_assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `{{schema}}`.`auth_assignment` (
  `item_name` VARCHAR(64) CHARACTER SET 'utf8mb3' NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` INT NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`item_name`, `user_id`),
  INDEX `fk_auth_assignment_user1_idx` USING BTREE (`user_id`) VISIBLE,
  CONSTRAINT `auth_assignment_ibfk_1`
    FOREIGN KEY (`item_name`)
    REFERENCES `{{schema}}`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_auth_assignment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `{{schema}}`.`user` (`id`))
ENGINE = InnoDB
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `{{schema}}`.`auth_item_child`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `{{schema}}`.`auth_item_child` (
  `parent` VARCHAR(64) CHARACTER SET 'utf8mb3' NOT NULL,
  `child` VARCHAR(64) CHARACTER SET 'utf8mb3' NOT NULL,
  PRIMARY KEY USING BTREE (`parent`, `child`),
  INDEX `child` USING BTREE (`child`) VISIBLE,
  CONSTRAINT `auth_item_child_ibfk_1`
    FOREIGN KEY (`parent`)
    REFERENCES `{{schema}}`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `auth_item_child_ibfk_2`
    FOREIGN KEY (`child`)
    REFERENCES `{{schema}}`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `{{schema}}`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `{{schema}}`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gender` VARCHAR(1) NULL DEFAULT NULL,
  `fullname` VARCHAR(145) NULL DEFAULT NULL,
  `nicename` VARCHAR(145) NULL DEFAULT NULL,
  `birthdate` DATE NULL DEFAULT NULL,
  `status` VARCHAR(145) NOT NULL DEFAULT 'Active',
  `created_at` INT NULL DEFAULT NULL,
  `updated_at` INT NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`id`),
  UNIQUE INDEX `id_UNIQUE` USING BTREE (`id`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `{{schema}}`.`intl_source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `{{schema}}`.`intl_source` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(255) NULL DEFAULT NULL,
  `message` TEXT NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `{{schema}}`.`intl_translation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `{{schema}}`.`intl_translation` (
  `id` INT NOT NULL,
  `language` VARCHAR(16) NOT NULL,
  `translation` TEXT NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`id`, `language`),
  INDEX `fk_message_source_message1_idx` USING BTREE (`id`) VISIBLE,
  CONSTRAINT `fk_term_message`
    FOREIGN KEY (`id`)
    REFERENCES `{{schema}}`.`intl_source` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `{{schema}}`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `{{schema}}`.`log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` INT NULL DEFAULT NULL,
  `updated_at` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`id`),
  UNIQUE INDEX `id_UNIQUE` USING BTREE (`id`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `{{schema}}`.`migration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `{{schema}}`.`migration` (
  `version` VARCHAR(180) NOT NULL,
  `apply_time` INT NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `{{schema}}`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `{{schema}}`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_id` INT(2) UNSIGNED ZEROFILL NULL,
  `name` VARCHAR(245) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `status` VARCHAR(145) NULL DEFAULT NULL,
  `created_at` INT NULL DEFAULT NULL,
  `updated_at` INT NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`id`),
  UNIQUE INDEX `id_UNIQUE` USING BTREE (`id`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
ROW_FORMAT = DYNAMIC;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;        
SQL_EOF;

    $dbName = Yii::$app->db->createCommand('SELECT DATABASE()')->queryScalar();
    $sql = str_replace('{{schema}}', $dbName, $sql);

    $this->execute($sql);
  }

  /**
   * {@inheritdoc}
   */
  public function safeDown()
  {
    echo "m251126_215754_init_schema cannot be reverted.\n";

    return false;
  }

  /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m251126_215754_init_schema cannot be reverted.\n";

        return false;
    }
    */
}
